### ISSUE TITLE
Clarify if web action or not.

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-index-tree#5]
## Overview
The action is currently not deployed as webaction. 

if this is intended:
- fix the readme
- improve the status monitoring for non-webactions

if this is not intended:
- deploy it _properly_

**Comment by trieloff** [comment]
This could be run as a web action, other than adobe/helix-index-big-tree#6 but for consistency I would treat both the same.

**Comment by tripodsan** [comment]
ok

**Comment by trieloff** [comment]
I still need to update the readme.

**Comment by rofe** [comment]
@trieloff can you update and close?
