### ISSUE TITLE
Monitor Setup is failling in CI

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-index-tree#6]
**Description**
see: https://circleci.com/gh/adobe/helix-index-tree/17

Also, since this is not a web-action, I doubt that our status check already works.
see #5

**Comment by rofe** [comment]
We don't currently have a solution for non-web actions. I suggest disabling monitoring in the CircleCI config for now.

**Comment by rofe** [comment]
If it were a web action, we'd also need https://github.com/adobe/helix-continuous/issues/50. See https://circleci.com/orbs/registry/orb/adobe/helix-post-deploy for documentation.

**Comment by rofe** [comment]
I recommend upgrading helix-status dependency to v5+. See also https://github.com/adobe/helix-continuous/tree/master/.circleci/orbs/helix-post-deploy

**Comment by rofe** [comment]
Per #5 this is not a web action by design, therefore our current monitoring can't be used.
